import { NextRequest, NextResponse } from 'next/server';
import { calculateFee, calculateTotal, isFirstInvoice, applyFirstInvoiceFree } from '@/lib/escrow/utils';
import { EscrowState, SUPPORTED_TOKENS, FEE_TIERS, ESCROW_TIMEOUTS } from '@/lib/escrow/types';
import { getDeadlineForState } from '@/lib/escrow/state-machine';
import { createClient } from '@supabase/supabase-js';

/**
 * POST /api/escrow/create
 * Create a new escrow invoice
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const {
      creator, // Seller wallet
      recipient, // Buyer wallet
      amount, // In token units (not including fee)
      token, // SOL, USDC, or USDT
      title,
      description,
      feeTier = 'FREE',
    } = body;

    // Validation
    if (!creator) {
      return NextResponse.json(
        { error: 'Creator (seller) wallet is required' },
        { status: 400 }
      );
    }

    if (!amount || isNaN(Number(amount)) || Number(amount) <= 0) {
      return NextResponse.json(
        { error: 'Amount must be greater than 0' },
        { status: 400 }
      );
    }

    // Recipient (buyer) is optional at creation - will be set when buyer accepts
    const buyerWallet = recipient || '';

    if (!token || !SUPPORTED_TOKENS[token as keyof typeof SUPPORTED_TOKENS]) {
      return NextResponse.json(
        { error: 'Invalid token. Supported: SOL, USDC, USDT' },
        { status: 400 }
      );
    }

    // Calculate fees
    const feeInfo = calculateFee(amount, feeTier as keyof typeof FEE_TIERS);
    const totalInfo = calculateTotal(amount, feeTier as keyof typeof FEE_TIERS);

    // Check if first invoice (fee waiver)
    const firstInvoice = await isFirstInvoice(creator);
    const firstInvoiceDiscount = applyFirstInvoiceFree(feeInfo.fee, firstInvoice);

    // Calculate deadlines (in milliseconds for frontend compatibility)
    const now = Date.now();
    // Start in DRAFT state - deadlines calculated when sent to buyer
    const acceptanceDeadline = getDeadlineForState(EscrowState.PENDING_ACCEPTANCE, now);
    const fundingDeadline = getDeadlineForState(EscrowState.ACCEPTED_WAITING_FUNDING, now);
    const reviewDeadline = getDeadlineForState(EscrowState.DELIVERED_REVIEW, now);

    // Create escrow record (to be stored in Supabase/on-chain)
    // Note: ID will be auto-generated by PostgreSQL as UUID
    const escrowData = {
      id: '', // Will be populated after insert
      version: 1,
      creator,
      recipient: buyerWallet,
      amount: Number(amount),
      tokenMint: SUPPORTED_TOKENS[token as keyof typeof SUPPORTED_TOKENS].mint,
      tokenSymbol: token,
      feeAmount: firstInvoiceDiscount.finalFee,
      feeOriginal: firstInvoiceDiscount.originalFee,
      feeDiscount: firstInvoiceDiscount.discount,
      isFirstInvoice: firstInvoice,
      feeTier,
      totalAmount: Number(amount) + firstInvoiceDiscount.finalFee,
      state: EscrowState.DRAFT, // Start in DRAFT, not PENDING_ACCEPTANCE
      title,
      description,
      createdAt: now,
      acceptanceDeadline,
      fundingDeadline,
      reviewDeadline,
      aiAnalysis: null,
      dispute: null,
    };

    // Save to Supabase
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    
    console.log('Creating escrow:', { creator, amount, token, title, hasSupabase: !!(supabaseUrl && supabaseServiceKey) });
    
    if (supabaseUrl && supabaseServiceKey) {
      const supabase = createClient(supabaseUrl, supabaseServiceKey);
      
      // Insert into escrows table with full schema
      // Note: Don't pass id - let PostgreSQL generate UUID
      const { data: insertData, error: escrowError } = await supabase
        .from('escrows')
        .insert([{
          creator_wallet: creator,
          buyer_wallet: buyerWallet,
          amount: Number(amount),
          token_mint: SUPPORTED_TOKENS[token as keyof typeof SUPPORTED_TOKENS].mint,
          token_symbol: token,
          fee_amount: firstInvoiceDiscount.finalFee,
          fee_original: firstInvoiceDiscount.originalFee,
          fee_discount: firstInvoiceDiscount.discount,
          fee_tier: feeTier,
          total_amount: Number(amount) + firstInvoiceDiscount.finalFee,
          state: EscrowState.DRAFT,
          title,
          description,
          acceptance_deadline: acceptanceDeadline,
          funding_deadline: fundingDeadline,
          review_deadline: reviewDeadline,
          is_first_invoice: firstInvoice,
          created_at: new Date().toISOString(),
        }]);
      
      if (escrowError) {
        console.error('Supabase insert error:', escrowError);
        return NextResponse.json(
          { error: 'Database error: ' + escrowError.message, details: escrowError },
          { status: 500 }
        );
      } else {
        console.log('Escrow saved to Supabase successfully');
        // Get the auto-generated UUID from the insert result
        const generatedId = insertData?.[0]?.id || '';
        escrowData.id = generatedId;
      }
    } else {
      console.warn('Supabase not configured - escrow created in memory only');
    }

    return NextResponse.json({
      success: true,
      escrow: escrowData,
      id: escrowData.id, // Use the generated/saved ID
      feeBreakdown: {
        amount,
        fee: firstInvoiceDiscount.finalFee,
        originalFee: firstInvoiceDiscount.originalFee,
        discount: firstInvoiceDiscount.discount,
        total: escrowData.totalAmount,
        isFirstInvoice: firstInvoice,
        tier: feeTier,
      },
      deadlines: {
        acceptance: new Date(acceptanceDeadline).toISOString(),
        funding: new Date(fundingDeadline).toISOString(),
        review: new Date(reviewDeadline).toISOString(),
      },
    });
  } catch (error: any) {
    console.error('Escrow create error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to create escrow' },
      { status: 500 }
    );
  }
}
